networks:
  microservices-network:
    driver: bridge

x-connection: &connection
  networks:
    - microservices-network
  env_file:
    - .env

# ////////////////////////////////////////
# _______________ SERVICES _______________
# ////////////////////////////////////////

services:

  kafka:
    <<: *connection
    image: apache/kafka:4.3.1    # Zookeeper = 3.x ; KRraft = 3.3+
    ports:
      - 9092:9092
    env_file:
      - ./kafka/.env   # overrides the anchor env location

  postgres:
    <<: *connection
    image: postgres:bookworm
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env   # overrides the anchor env location

  prometheus:
    <<: *connection
    image: prom/prometheus:main
    ports:
      - 9090:9090
    env_file:
      - ./prometheus/.env   # overrides the anchor env location

  grafana:
    <<: *connection
    image: grafana/grafana:11.3.0
    ports:
      - 3000:3000
    env_file:
      - ./grafana/.env   # overrides the anchor env location

  # ///////////////////////////////////////
  # ___________ CUSTOM SERVICES ___________
  # ///////////////////////////////////////

  user-service-db:
    image: postgres:17
    environment:
      POSTGRES_DB: user_service_db # always use underscore for this part
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data 
      # this means that the path to user-service-db-data is /var/lib/postgresql/data
      # so all db services will have same path, just different name like inventory-service-db-data ..

  frontend:
    <<: *connection
    build: ./frontend
    depends_on:
      - user-service
      - api-gateway-service
    ports:
      - "4200:80"

  api-gateway-service:
    <<: *connection
    build: ./api-gateway-service
    ports:
      - "8080:8080"

  discovery-service:
    <<: *connection
    build: ./discovery-service
    ports:
      - "8081:8081"

  user-service:
    <<: *connection
    build: ./user-service
    depends_on:
      - user-service-db
      - kafka
      - discovery-service
    ports:
      - "8082:8082"

  inventory-service:
    <<: *connection
    build: ./inventory-service
    depends_on:
      - inventory-service-db
      - kafka
      - discovery-service
    ports:
      - "8083:8083"

  procurement-service:
    <<: *connection
    build: ./procurement-service
    depends_on:
      - procurement-service-db
      - kafka
      - discovery-service
    ports:
      - "8084:8084"

  sales-service:
    <<: *connection
    build: ./sales-service
    depends_on:
      - sales-service-db
      - kafka
      - discovery-service
    ports:
      - "8085:8085"

  notification-service:
    <<: *connection
    build: ./notification-service
    depends_on:
      - kafka
      - discovery-service
    ports:
      - "8086:8086"

volumes:
  user-service-db-data:
  inventory-service-db-data:
  procurement-service-db-data:
  sales-service-db-data: