spring.application.name=api_gateway_service
server.port=${SERVER_PORT}

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_HOST}

# Gateway routes using Eureka service names
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://${EUREKA_HOST}:${USER_SERVICE_PORT}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Path=/businesses/**

spring.cloud.gateway.server.webflux.routes[1].id=INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://${EUREKA_HOST}:${INVENTORY_SERVICE_PORT}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory/**

spring.cloud.gateway.server.webflux.routes[2].id=SALES-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://${EUREKA_HOST}:${SALES_SERVICE_PORT}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/sales/**

spring.cloud.gateway.server.webflux.routes[3].id=PROCUREMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=http://${EUREKA_HOST}:${PROCUREMENT_SERVICE_PORT}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/procurement/**

spring.cloud.gateway.server.webflux.routes[4].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=http://${EUREKA_HOST}:${NOTIFICATION_SERVICE_PORT}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notification/**
# spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.netflix.discovery=DEBUG