# Build stage using official Temurin JDK 25
FROM eclipse-temurin:25-jdk AS builder

WORKDIR /app

# Install Maven manually
RUN apt-get update && apt-get install -y maven

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Runtime stage using Temurin JRE 25
FROM eclipse-temurin:25-jre
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]